### ISSUE TITLE
Getting 404

### ISSUE THREAD

**Issue by ebeauchamps** [lesaff/statamic-cachemanager#3]
I keep getting 404 pages when using this add-on (1.0.2) on the latest Statamic build (2.6.0 and 2.6.1)
A click on any on the 2 buttons/links send a 404 page

**Comment by rrelmy** [comment]
Statamic did change the addon route urls.
They are now no longer hardcoded in the widget

**Comment by ebeauchamps** [comment]
OK. But what are the routes that then must be added to routes.yaml in the settings?
